# Generated by Django 3.2 on 2022-01-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.CharField(max_length=64, null=True)),
                ('creation_ip', models.CharField(max_length=64, null=True)),
                ('input_dot', models.TextField()),
                ('dot_rep', models.TextField()),
                ('svg_rep', models.TextField()),
                ('svg_rep0', models.TextField(null=True)),
                ('svg_rep1', models.TextField(null=True)),
                ('svg_rep2', models.TextField(null=True)),
                ('svg_rep3', models.TextField(null=True)),
                ('status', models.TextField()),
                ('width', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('vis_type', models.CharField(max_length=64)),
                ('layout_algorithm', models.CharField(max_length=64)),
                ('cluster_algorithm', models.CharField(max_length=64)),
                ('contiguous_algorithm', models.CharField(max_length=64)),
                ('hyperbolic_projection', models.CharField(max_length=64)),
                ('color_scheme', models.CharField(max_length=64)),
                ('semantic_zoom', models.CharField(max_length=64)),
            ],
        ),
    ]
