# Generated by Django 3.2 on 2022-01-25 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='cluster_algorithm',
            new_name='convergence',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='contiguous_algorithm',
            new_name='iterations',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='semantic_zoom',
            new_name='opt_alpha',
        ),
    ]
